const data = [
    {
      "id": 1,
      "image":"comidas.jpg",
      "name": "Fiesta de las colectividades",
      "date": "2021-12-12",
      "description": "Disfruta de tus platos favoritos, de los diferentes paises, en un evento unico para toda la familia",
      "category":"Feria de Comida",
      "place": "Salón A",
      "capacity": 45000,
      "assistance":42756,
      "price": 5
    },
    {
      "id": 2,
      "image":"museo.jpg",
      "name": "Parque Jurásico",
      "date": "2021-11-02",
      "description": "Vamos al museo de paleontologia a hacer un recorrido increible para conocer los mas grandes dinosaurios",
      "category":"Salida al museo",
      "place": "Campo",
      "capacity": 82000,
      "assistance":65892,
      "price": 15
    },
    {
      "id": 3,
      "image":"disfraces.jpg",
      "name": "Noche de Halloween",
      "date": "2022-02-12",
      "description": "Ven con tu personaje disfras mas aterrador para ganar increibles premios",
      "category": "Fiesta de Disfraces",
      "place": "Salón C",
      "capacity": 12000,
      "estimate":9000,
      "price": 12
    },
    {
      "id": 4,
      "image":"musica.jpg",
      "name": "Metallica in concert",
      "date": "2022-01-22",
      "description": "Unico recital de la banda mas emblematica ",
      "category": "Concierto de Música",
      "place": "Salón A",
      "capacity": 138000,
      "estimate":138000,
      "price": 150
    },
    {
      "id": 5,
      "image":"maraton.jpg",
      "name": "10K por la vida",
      "date": "2021-03-01",
      "description": "Ven y haz ejercicio, mejora tu salud y tu estilo de vida",
      "category": "Carrera",
      "place": "Campo de Futból",
      "capacity": 30000,
      "assistance":25698,
      "price": 3
    },
    {
      "id": 6,
      "image":"libros.jpg",
      "name": "Feria del libro Escolar",
      "date": "2021-10-15",
      "description": "Trae tu libro escolar que ya no usas y lleva el que necesites",
      "category": "Intercambio de Libros",
      "place": "Salón D1",
      "capacity": 150000,
      "assistance":123286,
      "price": 1
    },
    {
      "id": 7,
      "image":"cine.jpg",
      "name": "Avengers",
      "date": "2022-10-15",
      "description": "Premier en 3d de Avengers de Marvel el inicio de una saga epica con tus mejores superheroes",
      "category": "Vamos al Cine",
      "place": "Salón D1",
      "capacity": 9000,
      "estimate":9000,
      "price": 250
    },
    {
      "id": 8,
      "image":"comidapetersen.jpg",
      "name": "Los Hermanos Pettersen",
      "date": "2021-02-11",
      "description": "Vení a probar sus mejores platos.",
      "category":"Feria de Comida",
      "place": "Salón A",
      "capacity": 45000,
      "assistance":42756,
      "price": 5
    },
    {
      "id": 9,
      "image":"museoanatomia.jpg",
      "name": "Museo Anatomía",
      "date": "2021-11-20",
      "description": "Vamos al museo de Anatomía a hacer un recorrido increible para conocer el cuerpo humano",
      "category":"Salida al museo",
      "place": "Campo",
      "capacity": 82000,
      "assistance":65892,
      "price": 19
    },
    {
      "id": 10,
      "image":"disfraces2.jpg",
      "name": "Fiesta de disfraces",
      "date": "2022-01-19",
      "description": "Vení a competir con tus mejores disfraces.",
      "category": "Fiesta de Disfraces",
      "place": "Salón C",
      "capacity": 12000,
      "estimate":9000,
      "price": 12
    },
    {
      "id": 11,
      "image":"musicaredhot.jpg",
      "name": "Red Hot Chilli Peppers in concert",
      "date": "2022-01-15",
      "description": "Unico recital de la banda mas emblematica.",
      "category": "Concierto de Música",
      "place": "Salón A",
      "capacity": 138000,
      "estimate":138000,
      "price": 450
    },
    {
      "id": 12,
      "image":"maratonnocturna.jpg",
      "name": "Maratón nocturna ",
      "date": "2021-12-31",
      "description": "Comenzá corriendo el año y disfrutando de la noche.",
      "category": "Carrera",
      "place": "Campo de Futból",
      "capacity": 30000,
      "assistance":25698,
      "price": 32
    },
    {
      "id": 13,
      "image":"ferialibro.jpg",
      "name": "Feria del libro",
      "date": "2021-09-15",
      "description": "Vení a renovar tus ejemplares.",
      "category": "Intercambio de Libros",
      "place": "Salón D1",
      "capacity": 150000,
      "assistance":123286,
      "price": 12
    },
    {
      "id": 14,
      "image":"cinegodfather.jpg",
      "name": "The Godfather",
      "date": "2022-09-10",
      "description": "Premier en 3D de la gran obra de Coppola",
      "category": "Vamos al Cine",
      "place": "Salón D1",
      "capacity": 9000,
      "estimate":9000,
      "price": 50
    },
    {
      "id": 15,
      "image":"comidabotana.jpg",
      "name": "Maru Bottana",
      "date": "2021-11-02",
      "description": "Vení a probar sus delicias y conocer a sus hijos!",
      "category":"Feria de Comida",
      "place": "Salón A",
      "capacity": 45000,
      "assistance":42756,
      "price": 5
    },
    {
      "id": 16,
      "image":"museokandinsky.jpg",
      "name": "Muestra Kandinsky",
      "date": "2021-11-02",
      "description": "Vení a ver sus grandes obras.",
      "category":"Salida al museo",
      "place": "Campo",
      "capacity": 82000,
      "assistance":65892,
      "price": 215
    },
    {
      "id": 17,
      "image":"disfraces80.jpg",
      "name": "Noche de los 80s",
      "date": "2022-02-12",
      "description": "Back to the 80s, venite acorde! ",
      "category": "Fiesta de Disfraces",
      "place": "Salón C",
      "capacity": 12000,
      "estimate":9000,
      "price": 18
    },
    {
      "id": 18,
      "image":"musicafloyd.jpg",
      "name": "Pink Floyd in concert",
      "date": "2022-01-12",
      "description": "Unico recital de la banda más emblematica ",
      "category": "Concierto de Música",
      "place": "Salón A",
      "capacity": 138000,
      "estimate":138000,
      "price": 250
    },
    {
      "id": 19,
      "image":"maratontrail.jpg",
      "name": "24k Trail Run",
      "date": "2021-03-01",
      "description": "Vení y probate en el mítico circuito de trail.",
      "category": "Carrera",
      "place": "Campo de Futból",
      "capacity": 30000,
      "assistance":25698,
      "price": 3
    },
    {
      "id": 20,
      "image":"librobonelli.jpg",
      "name": "Florencia Bonelli",
      "date": "2021-10-15",
      "description": "Florencia presentará su nuevo libro.",
      "category": "Intercambio de Libros",
      "place": "Salón D1",
      "capacity": 150000,
      "assistance":123286,
      "price": 10
    },
    {
      "id": 21,
      "image":"cinebatman.jpg",
      "name": "Batman Regresa",
      "date": "2022-11-29",
      "description": "Premier en 3D de Batman",
      "category": "Vamos al Cine",
      "place": "Salón D1",
      "capacity": 9000,
      "estimate":9000,
      "price": 250
    },
    
  ]